### ISSUE TITLE
onAppOpenAttribution not being called 

### ISSUE THREAD

**Issue by Aye-Myat-Mon** [AppsFlyerSDK/appsflyer-onelink-android-sample-apps#10]
onAppOpenAttribution not being called  after installing app from google play store for the first time by clicking the AppsFlyer link. So I can't get conversion data of onAppOpenAttribution. Help me please....

**Comment by liaz-af** [comment]
onAppOpenAttribution is only called when the app already installed. 
You can find more info here https://dev.appsflyer.com/hc/docs/android-legacy-apis

Thanks
