### ISSUE TITLE
Sample Code does not Build

### ISSUE THREAD

**Issue by mejohnsn** [AppsFlyerSDK/appsflyer-onelink-android-sample-apps#12]
I did a clone of the project to my own workspace (in Android Studio using https://github.com/AppsFlyerSDK/appsflyer-onelink-android-sample-apps.git) and I get an odd directory structure and error/warning messages like "This project does not use the Gradle build system" and "Frameworks detected". But I can see build.gradle in the directory tree, so it is clearly meant to use the Gradle build system, it just is not finding the files.

I also had to add a few things such as SDK in the Project Settings just to get this far. And I know "Frameworks detected" is a misleading error message caused by many different things, even something as simple is a mistake in directory structure. I am hoping this fix is that simple...

**Comment by liaz-af** [comment]
For future reference, pls make sure you open the `java/basic_app` directory in Android Studio
